config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "/home/about"=>"homes#about"

  devise_for :users

  # resources :users, only: [:index,:show,:edit,:update]
  # フォロー/フォロワー機能対応
  resources :users, only:[:index,:show,:edit,:update] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end
  
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  
  get "search" => "searches#search"
  
  post 'follow/:id' => 'relationships#follow', as: 'follow' 
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # belongs_to :books
  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  # フォロー/フォロワー機能
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
  # フォロー/フォロワー機能
  
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  
  
  def get_profile_image
   (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  
  # フォロー/フォロワー機能
  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    following_user.include?(user)
  end
  # フォロー/フォロワー機能
  
  # 検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  # 検索機能
  
  # def get_profile_image(width, height)
  #   unless profile_image.attached?
  #     file_path = Rails.root.join('app/assets/images/no_image.jpg')
  #     profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  #   end
  #   profile_image.variant(resize_to_limit: [width, height]).processed
  # end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    
    # フォロー/フォロワー機能
    @following_users = @user.following_user
    @follower_users = @user.follower_user
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    
    if @user != current_user
      redirect_to user_path(current_user.id)
    end      
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      # render "show"
      render :edit
    end
  end
  
  # フォロー・フォロワー機能
  def follows
    user = User.find(params[:id])
    @users = user.following_user
  end
  
  def followers
    user = User.find(params[:id])
    @users = user.follower_user
  end
  # フォロー・フォロワー機能
  
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <!-- 追加 -->
        <td>
          <%= link_to follows_user_path(user) do %>
            フォロー：<%= user.following_user.count %>
          <% end %>
        </td>
        
        <td>
          <%= link_to followers_user_path(user) do %>
            フォロワー：<%= user.follower_user.count %>
          <% end %>
        </td>
        <!-- 追加 -->
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn-sm btn-danger" %>
            <% else %>
              <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST, class:"btn-sm btn-success" %>
            <% end %>
           <% end %>
        </td>
        
        <td><%= link_to 'Show', user %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follow</th>
    <th><%= following_users.count %></th>
  </tr>
  <tr>
    <th>follower</th>
    <th><%= follower_users.count %></th>
  </tr>
</table>

  <% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn-sm btn-danger" %>
    <% else %>
      <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST, class:"btn-sm btn-success" %>
    <% end %>
    
  <% else %>
    <div class='row'>
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    </div>  
  <% end %>

app/views/users/edit.html.erb
<div class='container'>

  <div class='row'>
    <div class="col-md-5 mx-auto">
      <%= render 'searches/search' %>
    </div>
  </div>

  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class='container'>

  <div class='row'>
    <div class="col-md-5 mx-auto">
      <%= render 'searches/search' %>
    </div>
  </div>

  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Followers Users</h2>
       
    <table class='table'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %> 
          <tr>
            <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
            <td><%= user.name %></td>
            <!-- 追加 -->
            <td>
              <%= link_to follows_user_path(user) do %>
                フォロー：<%= user.following_user.count %>
              <% end %>
            </td>
            
            <td>
              <%= link_to followers_user_path(user) do %>
                フォロワー：<%= user.follower_user.count %>
              <% end %>
            </td>
            <!-- 追加 -->
            <td><%= link_to 'Show', user %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/users/follows.html.erb
<div class='container'>

  <div class='row'>
    <div class="col-md-5 mx-auto">
      <%= render 'searches/search' %>
    </div>
  </div>

  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Follows Users</h2>
       
    <table class='table'>
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %> 
          <tr>
            <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
            <td><%= user.name %></td>
            <!-- 追加 -->
            <td>
              <%= link_to follows_user_path(user) do %>
                フォロー：<%= user.following_user.count %>
              <% end %>
            </td>
            
            <td>
              <%= link_to followers_user_path(user) do %>
                フォロワー：<%= user.follower_user.count %>
              <% end %>
            </td>
            <!-- 追加 -->
            <td><%= link_to 'Show', user %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  
  <div class='row'>
    <div class="col-md-5 mx-auto">
      <%= render 'searches/search' %>
    </div>
  </div>
  
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user, following_users: current_user.following_user, follower_users: current_user.follower_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'users/index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>

  <div class='row'>
    <div class="col-md-5 mx-auto">
      <%= render 'searches/search' %>
    </div>
  </div>

  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user,following_users: @following_users,follower_users: @follower_users %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>