config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "/home/about"=>"homes#about"

  devise_for :users

  # resources :users, only: [:index,:show,:edit,:update]
  # フォロー/フォロワー機能対応
  resources :users, only:[:index,:show,:edit,:update] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end
  
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  
  get "search" => "searches#search"
  
  post 'follow/:id' => 'relationships#follow', as: 'follow' 
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  # has_many :user
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  # 検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  # 検索機能
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user.id)
    @post_comment = PostComment.new
    
    # フォロー/フォロワー機能
    @following_users = @user.following_user
    @follower_users = @user.follower_user
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    
    if @user != current_user
      redirect_to '/books'
    end
    
  end

  def update
    @book = Book.find(params[:id])
    @user = @book.user
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>

        <!-- fav機能一旦実装 →Update2023/04/06 非同期通信化に伴い部分テンプレート化 -->
        <td>
          <div id="favorite_btn_<%= book.id %>">
            <%= render 'favorites/favorite', book: book %>
          </div>
        </td>
        <!-- fav機能一旦実装 -->

        <td>
          <p><%= link_to "コメント: #{book.post_comments.count}", book_path(book.id) %></p>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  
  <div class='row'>
    <div class="col-md-5 mx-auto">
      <%= render 'searches/search' %>
    </div>
  </div>
  
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'layouts/errors', obj: @user %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  
  <div class='row'>
    <div class="col-md-5 mx-auto">
      <%= render 'searches/search' %>
    </div>
  </div>
  
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user, following_users: current_user.following_user, follower_users: current_user.follower_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  
  <div class='row'>
    <div class="col-md-5 mx-auto">
      <%= render 'searches/search' %>
    </div>
  </div>

  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user,following_users: @following_users,follower_users: @follower_users %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %>
              <% end %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%>
              <% end %>
            </td>

            <!-- fav機能一旦実装 →Update2023/04/06 非同期通信化に伴い部分テンプレート化 -->
            <td>
              <div id="favorite_btn_<%= @book.id %>">
                <%= render 'favorites/favorite', book: @book %>
              </div>
            </td>
            <!-- fav機能一旦実装 -->
            
            <!-- コメント機能一旦実装 -->
            <td>
              <p>コメント：<%= @book.post_comments.count %></p>
            </td>
            <!-- コメント機能一旦実装 -->
            
        </tr>
      </table>
      
      <!-- コメント機能一旦実装 -->
      <div>
        <% @book.post_comments.each do |post_comment| %>
          <p>
            <%= image_tag post_comment.user.get_profile_image, size:"50x50" %>
            
            <%= post_comment.comment %>
            <% if post_comment.user == current_user %>
              <%= link_to "Destroy", book_post_comment_path(post_comment.book, post_comment), method: :delete , class: "btn btn-danger" %>
            <% end %>
            
          </p>
          User: <%= link_to post_comment.user.name, user_path(post_comment.user) %> <br>
          <br>
        <% end %>
      </div>
      
      <br>
      
      <div>
        <%= form_with model: [@book, @post_comment] do |f| %>
          <p>
          <%= f.text_area :comment, cols: '120', rows: '5', placeholder: "コメントここ" %><br>
          <%= f.submit "送信" %>
          </p>
        <% end %>
      </div>
    <!-- コメント機能一旦実装 -->
    
    </div>
  </div>
</div>